name: Run Haskell Tests
author: Simon Hengel
description: Run all tests of a Haskell package

branding:
  icon: check-square
  color: green

inputs:
  caching:
    description: Cache dependencies
    required: false
    default: false
  strict:
    description: Run with --strict
    required: false
    default: false

runs:
  using: composite
  steps:
    - shell: bash
      run: cabal update

    - shell: bash
      run: "[ -f cabal.project ] || cabal configure --enable-tests --enable-benchmarks"

    - shell: bash
      run: cabal build all --dry-run
      if: inputs.caching == 'true'

    - shell: bash
      run: echo "version=`ghc --numeric-version`" >> $GITHUB_OUTPUT
      id: ghc
      if: inputs.caching == 'true'

    - shell: bash
      run: echo "store-dir=`cabal -v0 path --store-dir`" >> $GITHUB_OUTPUT
      id: cabal-path
      if: inputs.caching == 'true'

    - uses: actions/cache/restore@v3
      id: cache
      env:
        key: ${{ runner.os }}-ghc-${{ steps.ghc.outputs.version }}
      with:
        path: ${{ steps.cabal-path.outputs.store-dir }}
        key: ${{ env.key }}-${{ hashFiles('dist-newstyle/cache/plan.json') }}
        restore-keys: ${{ env.key }}-
      if: inputs.caching == 'true'

    - shell: bash
      run: cabal build all --only-dependencies
      if: inputs.caching == 'true'

    - uses: actions/cache/save@v3
      with:
        path: ${{ steps.cabal-path.outputs.store-dir }}
        key: ${{ steps.cache.outputs.cache-primary-key }}
      if: inputs.caching == 'true' && steps.cache.outputs.cache-hit != 'true'

    - shell: bash
      run: cabal build all

    - shell: bash
      run: echo "HSPEC_STRICT=yes" >> $GITHUB_ENV
      if: inputs.strict == 'true'
    - shell: bash
      run: cabal test all --test-show-details=direct
